#define FONT_SIZE 12
#define BORDER_RADIUS 8
#define BAR_HEIGHT 30
#define MAX_CLIENTS 2

#define BORDER_GAP 16
#define GAP_SIZE 5
#define MAX_WINDOWS 2
#define MAX_WINDOWS_PER_ROW 2
// #define MAX_WINDOWS_PER_COLUMN 2
